### PR TITLE
Add more supported formats to FFmpeg decoder

### PR DESCRIPTION
**Pull request by diizzyy**
Add a bunch of supported formats to FFmpeg decoder to reduce amount of dependencies

### CODE REVIEW

**Comment by diizzyy** [comment]
Just a simple attempt to use less dependencies, I'm not sure if all formats works as intended.

**Comment by tomscii** [comment]
Not wanting to speak on behalf of Jeremy, but my $.02 is that this cannot be accepted in its current form.

1. What is your problem with dependencies and why is this the right solution to that problem?

All libraries are accessible (distro-provided) so installing them should not be a problem for anyone. And I see no point in using ffmpeg to decode e.g., flac instead of the flac library - ffmpeg either uses the same flac library under the hood (so now you have the same dependency, only transitive), or the flac library is preferable as it is the reference implementation. But that is just one of many possible examples. You have given absolutely no explanation why you want to do this, and I cannot see any good reason myself.

2. At the very least, you are expected to test all these formats and make sure that they all work. Otherwise you are breaking the program for others.

**Comment by diizzyy** [comment]
1. According source code and configure options (I looked at 4.4.4 and 6.0) there's no such option regarding FLAC. FFmpeg always relies on its native implementation. I'm not sure about your argument about preference, by looking at the source code I never at least intentionally removed the ability to use FLAC if you so prefer, it merely adds the ability to use FFmpeg as backend instead. Apart from the dependency benefit I suppose I also should've mentioned performance for example which is quite a bit better looking at multiple different libraries used for various formats.

A few quick tests on my x86 (amd64) box using FFmpeg 6.0.

```
flac 1.4.2
/usr/bin/time -h flac -t test.flac
11.86s real             11.66s user             0.15s sys

/usr/bin/time -h ffmpeg -i test.flac -f null -
4.86s real              6.74s user              0.37s sys

libmad 0.16.3 (speed option enabled), madplay 0.15.2
/usr/bin/time madplay -o /dev/null test.mp3
11.01 real        10.92 user         0.03 sys

/usr/bin/time -h ffmpeg -i test.mp3 -f null -
5.29s real              5.53s user              0.61s sys

oggdec 1.4.2, libvorbis 1.3.7
/usr/bin/time -h oggdec -o /dev/null test.ogg
15.94s real             15.07s user             0.55s sys

/usr/bin/time -h ffmpeg -i test.ogg -f null -
7.61s real              7.94s user              1.30s sys
```

2. As I stated previously I haven't been able to test all formats and I never made any claims that everything worked as expected for which I was waiting feedback on.

**Comment by tomscii** [comment]
@diizzyy It would have been a little bit different if you had provided this up front - I thought you wanted Aqualung to rely on less external libraries, hence my initial response. (And regarding your benchmarks, deciding whether using ffmpeg instead of those dedicated libs is preferable would be a much broader topic, let's not go there.)

@jeremyevans Agreed - feel free to merge it. It's a bit difficult to know exactly what files ffmpeg will be able to decode; we've been on the conservative side here for sure.

**Comment by jeremyevans** [comment]
OK, I'm going to merge this.

**Pull request merged**
